### ISSUE TITLE
interpolations error 

### ISSUE THREAD

**Issue by vincelhx** [vincelhx/Sentinel1_recalibration#3]
_sometimes :_
``` 
Traceback (most recent call last):
  File "/home1/datahome/vlheureu/git/Sentinel1_recalibration/Sentinel1_recalibration/scripts/script_grd.py", line 244, in <module>
    processor_grd()
  File "/home1/datahome/vlheureu/git/Sentinel1_recalibration/Sentinel1_recalibration/scripts/script_grd.py", line 236, in processor_grd
    recalibrate_grd(input_file, args.aux_version_config, config_file = None, resolution = args.resolution, save_netcdf=args.save_netcdf,
  File "/home1/datahome/vlheureu/git/Sentinel1_recalibration/Sentinel1_recalibration/scripts/script_grd.py", line 97, in recalibrate_grd
    array_geap_old[current_indices] = interp_geap_old(
  File "/home1/datawork/vlheureu/conda-env/xsar_N3/lib/python3.10/site-packages/scipy/interpolate/_polyint.py", line 80, in __call__
    y = self._evaluate(x)
  File "/home1/datawork/vlheureu/conda-env/xsar_N3/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 755, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home1/datawork/vlheureu/conda-env/xsar_N3/lib/python3.10/site-packages/scipy/interpolate/_interpolate.py", line 789, in _check_bounds
    raise ValueError("A value ({}) in x_new is above "
ValueError: A value (15.03477176497298) in x_new is above the interpolation range's maximum value (15.0).
INFO:prun:[2023-11-23T16:46:20Z] End of processing for input line 1 : '/home/datawork-cersat-public/cache/project/sarwave/data/products/tests/recalibrated_data_from_mpc_kersten/original_data/S1B_IW_GRDH_1S
DV_20170711T170628_20170711T170653_006443_00B539_29A5.SAFE'. EXIT_CODE=1
```

**Comment by vincelhx** [comment]
``` python
            array_geap_old[current_indices] = interp_geap_old(
                offboresightAngle.values[current_indices])
```

**Comment by vincelhx** [comment]
why not always this error ?
